[workspace]
resolver = "2"
members = [
    "crates/logirecon",
    "crates/logirecon_iced",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["sicheng<sicheng1806@outlook.com>"]

[workspace.dependencies]
logirecon = { version = "0.2.0", path = "./crates/logirecon" }

calamine = { version = "0.35.0", features = ["chrono"] }
chrono = { version = "0.4.41", features = ["std"] }
polars = { version = "0.53.0", features = [
    "lazy",
    "round_series",
    "strings",
    "dtype-struct",
    "regex",
    "concat_str",
    "dtype-categorical","dtype-u8","abs", "csv"
] }
polars_excel_writer = "0.25.0"
rust_xlsxwriter = "0.95.0"
tokio = {version = "1.52.3"}
uuid = {version = "1.23.3", features = ["v4", "fast-rng", "serde", "js"]}

thiserror = "2.0.18"
anyhow = "1.0.102"
tracing = {version = "0.1.44"}
tracing-subscriber = {version = "0.3.23", features = ["env-filter"]}
tracing-appender = "0.2.5"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150" }
