[package]
name = "logirecon"
version = "0.1.0"
edition = "2024"
description = "物流对账分析工具，支持Excel数据导入、自动核对和报表生成"
authors = ["sicheng<sicheng1806@outlook.com>"]

[dependencies]
calamine = { version = "0.35.0", features = ["chrono"] }
chrono = { version = "0.4.41", features = ["std"] }
env_logger = "0.11.10"
log = "0.4.30"
polars = { version = "0.53.0", features = [
    "lazy",
    "round_series",
    "strings",
    "dtype-struct",
    "regex",
    "concat_str",
    "dtype-categorical","dtype-u8","abs"
] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
slint = "1.16.1"
# 在slint 1.17 版本后删除此依赖
icu_provider = { version = "2", features = ["logging"] }

[build-dependencies]
slint-build = "1.16.1"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# # Enable a large amount of optimization in the dev profile for dependencies.
# [profile.dev.package."*"]
# opt-level = 3

[profile.release]
codegen-units = 1
lto = true
