[package]
name = "logirecon_gui"
description = "logirecon的GUI工具，基于Iced"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
logirecon_core.workspace = true

calamine.workspace = true
polars.workspace = true
polars_excel_writer.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing-subscriber.workspace = true

iced.workspace = true
rfd = {version = "0.17.2"}
uuid = {version = "1.23.3", features = ["v4", "fast-rng", "serde"]}
directories = {version = "6.0.0"}
